version: '3'
 
services:
    web:
      build: .
      volumes:
        - .:/src
      command: bash -c "cd src/; python main.py"
      ports:
        - "80:80"
      depends_on:
        - redis
    redis:
      image: "redis"
      ports:
        - "6379:6379"
      volumes:
        - 'redis_data:/data'

volumes:
  redis_data: