version: '3'
 
services:
    web:
      build: .
      volumes:
        - .:/src
      ports:
        - "80:80"
      depends_on:
        - redis
    redis:
      image: "redis"
      volumes:
        - 'redis_data:/data'

volumes:
  redis_data: